### ISSUE TITLE
No environments in the code

### ISSUE THREAD

**Issue by mohitsharma0690** [jangirrishabh/look-closer#1]
Hi,

There doesn't seem to be any environments provided in the github repo. Can you please add the envs, since it seems that the paper has custom envs (I am assuming this is possible but please let me know if it is not)?

**Comment by jangirrishabh** [comment]
Hi,

That was a gitignore error. Thank you for letting us know! You should be able to see the envs now.
Please let us know if there is any other problems.

**Comment by mohitsharma0690** [comment]
Thanks a lot.
